### ISSUE TITLE
Avali are transparent for some reason

### ISSUE THREAD

**Issue by NinekoTheCat** [NesiTheAvali/RimVali-Core#4]
**Describe the bug**
the avali pawns are not able to be seen, but their names still exist

**To Reproduce**
1. Create a new world
2. spawn in
3. observe

**Expected behavior**
avali should be seeable

**Screenshots**
![image](https://user-images.githubusercontent.com/45885710/151877143-3cbb3611-cc63-46a9-862a-a0e5776b5d92.png)

**Versions:**
 - 1.3.3200
- Mod version Kisu 1.1.0

**Additional context**
OS : Linux-5.15.15-76051515-generic 
I have these mods:
Dubs break mod
Dubs bad hygene
Dubs central heating
Dubs mint menus
Rimvali: Core
Rimvali: Beta
Rimvali: Cuisine

**Comment by Toby222** [comment]
Are they wearing Ideology-stylized apparel? (Spikecore jackets and the like)
And is there anything in the logs?

**Comment by NinekoTheCat** [comment]
The logs only mention that the same package ID is loaded twice, but other than that no not really, I stripped one naked, and they still weren't rendering. Heck, I created a new colony, and it still wasn't rendering.

> Are they wearing Ideology-stylized apparel? (Spikecore jackets and the like) And is there anything in the logs?

**Comment by NinekoTheCat** [comment]
and I made the second one with the rimworld classic ideology setting

> Are they wearing Ideology-stylized apparel? (Spikecore jackets and the like) And is there anything in the logs?

**Comment by Toby222** [comment]
> The logs only mention that the same package ID is loaded twice [...]

Do you have both RimVali: Far From Avalon and RimVali: Beta installed simultaneously?
They share the same modId, so having them both causes errors in loading.

**Comment by NinekoTheCat** [comment]
> > The logs only mention that the same package ID is loaded twice [...]
> 
> Do you have both RimVali: Far From Avalon and RimVali: Beta installed simultaneously? They share the same modId, so having them both causes errors in loading.

I will remove one of them and see if that helps

**Comment by NinekoTheCat** [comment]
No it did not

**Comment by NinekoTheCat** [comment]
Update: Every pawn is transparent

**Comment by RecompiledBirds** [comment]
As it currently stands, I do not have a linux installation with which I could test/fix this issue.

Anyone else is free to work on it.
